#!/bin/bash

platform=$(uname -s)
echo "Platform: $platform"
target=$1

if [[ $platform == *Darwin* ]]; then
    target="macos"
elif [[ $platform == *Linux* ]]; then
    target="linux"
elif [[ $platform == *NT* ]]; then
    target="windows"
else
    echo "Unknown platform: $platform"
    exit 1
fi

# ------------------------------------------------------------------------------

echo "Running pub get"
flutter pub get
echo "Building rust code"
flutter_rust_bridge_codegen generate
echo "Building flutter app"
flutter build $target
