#!/bin/bash

platform=$(uname -s)
echo "Platform: $platform"
target=$1

if [[ $platform == *Darwin* ]]; then
    target="macos"
elif [[ $platform == *Linux* ]]; then
    target="linux"
elif [[ $platform == *NT* ]]; then
    target="windows"
else
    echo "Unknown platform: $platform"
    exit 1
fi

# ------------------------------------------------------------------------------

echo "Generating files"
if [[ $platform == *NT* ]]; then
    sh generate_files
else
    ./generate_files
fi

echo "Building flutter app"
flutter build $target
