#!/bin/bash

# https://distributor.leanflutter.dev/getting-started/

# ------------------------------------------------------------------------------

clean() {
    rm -rf $1
}

# if output=$(clean build); then
#     echo "Cleaned up build"
# else
#     echo "Failed to clean up build"
#     exit 1
# fi

if output=$(clean dist); then
    echo "Cleaned up dist"
else
    echo "Failed to clean up dist"
    exit 1
fi

# ------------------------------------------------------------------------------

platform=$(uname -s)
echo "Platform: $platform"
target=$1
extension="bat"

if [[ $platform == *Darwin* ]]; then
    target="macos"
    extension=""
elif [[ $platform == *Linux* ]]; then
    target="linux"
    extension=""
elif [[ $platform == *NT* ]]; then
    target="windows"
    extension=".bat"
elif [[ target == "android" ]]; then
    exit 1
elif [[ target == "ios" ]]; then
    exit 1
else
    echo "Unknown platform: $platform"
    exit 1
fi

# ------------------------------------------------------------------------------

echo "Generating files"
if [[ $platform == *NT* ]]; then
    sh ./generate_files
else
    ./generate_files
fi

echo "Updating flutter_distributor"
flutter_distributor$extension upgrade

echo "Running: flutter_distributor.$extension release --name $target"
flutter_distributor$extension release --name $target
